from config import RAW_PRICES_PATH, RETURNS_PATH, PRICES_LONG_PATH, AVAILABILITY_PATH, VOLUME_PATH, LIQUIDITY_PATH, UNIVERSE_PATH,FORWARD_RETURNS_PATH
import os

for f in [RAW_PRICES_PATH, RETURNS_PATH, PRICES_LONG_PATH, AVAILABILITY_PATH, VOLUME_PATH, LIQUIDITY_PATH, UNIVERSE_PATH,FORWARD_RETURNS_PATH]:
    if os.path.exists(f):
        os.remove(f)
        print(f"Deleted: {f}")

