import os

from config import (
    AVAILABILITY_PATH,
    DATA_AUDIT_REPORT_PATH,
    DATA_AUDIT_SUMMARY_PATH,
    DATA_AVAILABILITY_TIMELINE_PATH,
    FORWARD_RETURNS_PATH,
    HISTORICAL_COMPONENTS_PATH,
    LIQUIDITY_PATH,
    MEMBERSHIP_PATH,
    PRICES_LONG_PATH,
    QUALITY_PATH,
    RAW_PRICES_PATH,
    RETURNS_PATH,
    RISK_FREE_RATE_PATH,
    UNIVERSE_PATH,
    VOLUME_PATH,
    VOLUME_QUALITY_PATH,
)


GENERATED_DATA_PATHS = (
    RAW_PRICES_PATH,
    RETURNS_PATH,
    PRICES_LONG_PATH,
    AVAILABILITY_PATH,
    QUALITY_PATH,
    MEMBERSHIP_PATH,
    VOLUME_PATH,
    VOLUME_QUALITY_PATH,
    LIQUIDITY_PATH,
    UNIVERSE_PATH,
    HISTORICAL_COMPONENTS_PATH,
    FORWARD_RETURNS_PATH,
    RISK_FREE_RATE_PATH,
    DATA_AUDIT_REPORT_PATH,
    DATA_AUDIT_SUMMARY_PATH,
    DATA_AVAILABILITY_TIMELINE_PATH,
)


def delete_generated_data():
    for path in GENERATED_DATA_PATHS:
        if os.path.exists(path):
            os.remove(path)
            print(f"Deleted: {path}")


if __name__ == "__main__":
    delete_generated_data()
